const axios = require("axios");

function getGithubApi() {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error("GITHUB_TOKEN missing in .env");
  }

  return axios.create({
    baseURL: "https://api.github.com",
    timeout: 120000,
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });
}

function cleanRepoName(name) {
  return (
    String(name || "generated-app")
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40) || "generated-app"
  );
}

function toBase64(content) {
  return Buffer.from(String(content || ""), "utf8").toString("base64");
}

async function createRepo(api, repoName, description) {
  console.log("Creating GitHub repo:", repoName);

  const response = await api.post("/user/repos", {
    name: repoName,
    private: false,
    auto_init: false,
    description: description || "Generated project",
  });

  return response.data;
}

async function uploadFile(api, owner, repo, filePath, content) {
  console.log("Uploading to GitHub:", filePath);

  await api.put(`/repos/${owner}/${repo}/contents/${filePath}`, {
    message: `Add ${filePath}`,
    content: toBase64(content),
  });
}

/**
 * STATIC WEBSITE PUSH
 * Used by POST /api/deploy
 */
async function pushWebsiteToGithub(projectName, html, css, js) {
  if (!html || !html.trim()) {
    throw new Error("Missing HTML content");
  }

  const api = getGithubApi();

  const userRes = await api.get("/user");
  const owner = userRes.data.login;

  const repoName = `${cleanRepoName(projectName)}-${Date.now()}`;

  const repoData = await createRepo(
    api,
    repoName,
    `Static website generated by Prompt2Site`
  );

  const files = {
    "index.html": html,
    "style.css": css || "",
    "script.js": js || "",
    "README.md": `# ${projectName || "Static Website"}

Generated static website.

## Files

- index.html
- style.css
- script.js
`,
  };

  for (const [filePath, content] of Object.entries(files)) {
    await uploadFile(api, owner, repoName, filePath, content);
  }

  const githubUrl = repoData.html_url;

  console.log("GitHub upload completed:", {
    repoName,
    githubUrl,
  });

  return {
    success: true,
    repoName,
    githubUrl,
    owner,
  };
}

/**
 * FULL-STACK PROJECT PUSH
 * Used by POST /api/fullstack/deploy
 * Used by POST /api/fullstack/generate-deploy
 */
async function pushFullStackToGithub(projectName, code) {
  if (!code || typeof code !== "object") {
    throw new Error("Full-stack code missing");
  }

  if (!code.frontend || !code.backend) {
    throw new Error("Full-stack code must contain frontend and backend");
  }

  if (!code.frontend.appJsx) {
    throw new Error("Frontend App.jsx missing");
  }

  if (!code.backend.serverJs) {
    throw new Error("Backend server.js missing");
  }

  const api = getGithubApi();

  const userRes = await api.get("/user");
  const owner = userRes.data.login;

  const repoName = `${cleanRepoName(projectName)}-fullstack-${Date.now()}`;

  const repoData = await createRepo(
    api,
    repoName,
    `Full-stack app generated by Prompt2Site`
  );

  const frontendPackageJson =
    code.frontend.packageJson ||
    JSON.stringify(
      {
        name: `${cleanRepoName(projectName)}-frontend`,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          "@vitejs/plugin-react": "^4.2.1",
          vite: "^5.0.0",
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          axios: "^1.6.0",
        },
        devDependencies: {},
      },
      null,
      2
    );

  const backendPackageJson =
    code.backend.packageJson ||
    JSON.stringify(
      {
        name: `${cleanRepoName(projectName)}-backend`,
        version: "1.0.0",
        main: "server.js",
        scripts: {
          start: "node server.js",
          dev: "nodemon server.js",
        },
        dependencies: {
          express: "^4.18.2",
          cors: "^2.8.5",
          dotenv: "^16.4.5",
          mongoose: "^8.0.0",
        },
        devDependencies: {
          nodemon: "^3.0.0",
        },
      },
      null,
      2
    );

  const files = {
    "README.md": `# ${projectName || "Full Stack App"}

Generated full-stack project.

## Frontend

\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`

## Backend

\`\`\`bash
cd backend
npm install
npm start
\`\`\`
`,

    ".gitignore": `node_modules
.env
dist
build
.DS_Store
`,

    "frontend/package.json": frontendPackageJson,

    "frontend/index.html":
      code.frontend.indexHtml ||
      `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName || "Full Stack App"}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,

    "frontend/src/main.jsx":
      code.frontend.mainJsx ||
      `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./App.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,

    "frontend/src/App.jsx": code.frontend.appJsx,

    "frontend/src/App.css":
      code.frontend.appCss ||
      `body {
  margin: 0;
  font-family: system-ui, Arial, sans-serif;
}

.app {
  padding: 30px;
}`,

    "frontend/vite.config.js":
      code.frontend.viteConfig ||
      `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});`,

    "backend/package.json": backendPackageJson,

    "backend/server.js": code.backend.serverJs,

    "backend/.env.example": `PORT=5000
MONGO_URI=your_mongodb_connection_string
`,
  };

  for (const [filePath, content] of Object.entries(files)) {
    await uploadFile(api, owner, repoName, filePath, content);
  }

  const githubUrl = repoData.html_url;

  console.log("Full-stack GitHub upload completed:", {
    repoName,
    githubUrl,
  });

  return {
    success: true,
    repoName,
    githubUrl,
    owner,
  };
}

module.exports = {
  pushWebsiteToGithub,
  pushFullStackToGithub,
};