const axios = require("axios");

function getGithubApi() {
  if (!process.env.GITHUB_TOKEN) throw new Error("GITHUB_TOKEN missing in .env");
  return axios.create({
    baseURL: "https://api.github.com",
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github.v3+json",
    },
  });
}

function toBase64(content) {
  // Convert content to string if it's not already
  const stringContent = typeof content === 'string' ? content : JSON.stringify(content);
  return Buffer.from(stringContent || "", "utf8").toString("base64");
}

function cleanRepoName(name) {
  return String(name || "website")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 45);
}

async function getGithubUsername() {
  if (process.env.GITHUB_USERNAME) return process.env.GITHUB_USERNAME;
  const githubApi = getGithubApi();
  const res = await githubApi.get("/user");
  return res.data.login;
}

async function createGithubRepo(repoName) {
  const githubApi = getGithubApi();
  console.log(`📁 Creating GitHub repo: ${repoName}`);
  
  const response = await githubApi.post("/user/repos", {
    name: repoName,
    description: "Generated by Prompt2Site",
    private: false,
    auto_init: false,
  });
  
  console.log(`✅ GitHub repo created: ${response.data.html_url}`);
  return {
    repoUrl: response.data.html_url,
    cloneUrl: response.data.clone_url,
  };
}

async function uploadFileToGithub(repoName, filePath, content) {
  const githubApi = getGithubApi();
  const username = await getGithubUsername();
  
  // Ensure content is a string
  let stringContent = content;
  if (typeof content !== 'string') {
    stringContent = JSON.stringify(content, null, 2);
  }
  
  let sha = null;
  try {
    const existing = await githubApi.get(`/repos/${username}/${repoName}/contents/${filePath}`);
    sha = existing.data.sha;
  } catch (error) {
    // File doesn't exist, continue
    if (error.response?.status !== 404) {
      console.log(`⚠️ Error checking file ${filePath}:`, error.message);
    }
  }
  
  await githubApi.put(`/repos/${username}/${repoName}/contents/${filePath}`, {
    message: `Add/Update ${filePath}`,
    content: toBase64(stringContent),
    sha: sha || undefined,
    branch: "main",
  });
  
  console.log(`✅ Uploaded: ${filePath}`);
}

async function pushWebsiteToGithub(projectName, files) {
  if (!files || !files.html) {
    throw new Error("Missing HTML content");
  }

  const repoName = `${cleanRepoName(projectName)}-${Date.now()}`;
  const repo = await createGithubRepo(repoName);
  
  await uploadFileToGithub(repoName, "index.html", files.html);
  
  if (files.css && files.css.trim()) {
    await uploadFileToGithub(repoName, "style.css", files.css);
  }
  
  if (files.js && files.js.trim()) {
    await uploadFileToGithub(repoName, "script.js", files.js);
  }
  
  const readme = `# ${projectName}

## Static Website Generated by Prompt2Site

### Files
- index.html
- style.css  
- script.js

---
Generated with ❤️ using Prompt2Site`;
  
  await uploadFileToGithub(repoName, "README.md", readme);
  
  return {
    repoName: repoName,
    githubUrl: repo.repoUrl,
    success: true,
  };
}

async function pushFullStackToGithub(projectName, fullStackCode) {
  if (!fullStackCode?.frontend || !fullStackCode?.backend) {
    throw new Error("Missing frontend or backend code");
  }

  const repoName = `${cleanRepoName(projectName)}-fullstack-${Date.now()}`;
  const repo = await createGithubRepo(repoName);

  // Upload README
  const readmeContent = fullStackCode.readme || `# ${projectName}\n\n## Full-Stack Application\n\nGenerated by Prompt2Site\n\n### Project Structure\n- Frontend: React + Vite\n- Backend: Node.js + Express\n\n### Deployment\n1. Deploy backend to Render\n2. Deploy frontend to Netlify\n3. Add VITE_API_URL environment variable`;
  await uploadFileToGithub(repoName, "README.md", readmeContent);

  // Upload frontend files
  await uploadFileToGithub(repoName, "frontend/package.json", fullStackCode.frontend.packageJson);
  await uploadFileToGithub(repoName, "frontend/index.html", fullStackCode.frontend.indexHtml);
  await uploadFileToGithub(repoName, "frontend/src/main.jsx", fullStackCode.frontend.mainJsx);
  await uploadFileToGithub(repoName, "frontend/src/App.jsx", fullStackCode.frontend.appJsx);
  await uploadFileToGithub(repoName, "frontend/src/App.css", fullStackCode.frontend.appCss);

  // Upload backend files
  await uploadFileToGithub(repoName, "backend/package.json", fullStackCode.backend.packageJson);
  await uploadFileToGithub(repoName, "backend/server.js", fullStackCode.backend.serverJs);
  await uploadFileToGithub(repoName, "backend/.env.example", fullStackCode.backend.envExample || "PORT=5000\nMONGODB_URI=mongodb://localhost:27017/app");
  
  // Create .gitignore
  const gitignore = `node_modules/
.env
dist/
.DS_Store
*.log`;
  await uploadFileToGithub(repoName, ".gitignore", gitignore);

  console.log(`✅ Full-stack project pushed to GitHub: ${repo.repoUrl}`);
  
  return {
    repoName: repoName,
    githubUrl: repo.repoUrl,
    success: true,
  };
}

module.exports = {
  pushWebsiteToGithub,
  pushFullStackToGithub,
  getGithubUsername,
  createGithubRepo,
  uploadFileToGithub
};